/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE_SEMI = 3,
  anon_sym_type = 4,
  anon_sym_EQ = 5,
  anon_sym_SEMI = 6,
  anon_sym_struct = 7,
  anon_sym_union = 8,
  sym_identifier = 9,
  sym_source_file = 10,
  sym_module_definition = 11,
  sym_module_name = 12,
  sym_module_body = 13,
  sym_type_definition = 14,
  sym_type_name = 15,
  sym_type_body = 16,
  sym_struct_definition = 17,
  sym_struct_name = 18,
  sym_struct_body = 19,
  sym_struct_field = 20,
  sym_union_definition = 21,
  sym_union_name = 22,
  sym_union_body = 23,
  sym_union_field = 24,
  sym_field_type = 25,
  sym_field_name = 26,
  aux_sym_module_body_repeat1 = 27,
  aux_sym_struct_body_repeat1 = 28,
  aux_sym_union_body_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE_SEMI] = "};",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_struct] = "struct",
  [anon_sym_union] = "union",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_module_definition] = "module_definition",
  [sym_module_name] = "module_name",
  [sym_module_body] = "module_body",
  [sym_type_definition] = "type_definition",
  [sym_type_name] = "type_name",
  [sym_type_body] = "type_body",
  [sym_struct_definition] = "struct_definition",
  [sym_struct_name] = "struct_name",
  [sym_struct_body] = "struct_body",
  [sym_struct_field] = "struct_field",
  [sym_union_definition] = "union_definition",
  [sym_union_name] = "union_name",
  [sym_union_body] = "union_body",
  [sym_union_field] = "union_field",
  [sym_field_type] = "field_type",
  [sym_field_name] = "field_name",
  [aux_sym_module_body_repeat1] = "module_body_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_union_body_repeat1] = "union_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE_SEMI] = anon_sym_RBRACE_SEMI,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_union] = anon_sym_union,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_module_definition] = sym_module_definition,
  [sym_module_name] = sym_module_name,
  [sym_module_body] = sym_module_body,
  [sym_type_definition] = sym_type_definition,
  [sym_type_name] = sym_type_name,
  [sym_type_body] = sym_type_body,
  [sym_struct_definition] = sym_struct_definition,
  [sym_struct_name] = sym_struct_name,
  [sym_struct_body] = sym_struct_body,
  [sym_struct_field] = sym_struct_field,
  [sym_union_definition] = sym_union_definition,
  [sym_union_name] = sym_union_name,
  [sym_union_body] = sym_union_body,
  [sym_union_field] = sym_union_field,
  [sym_field_type] = sym_field_type,
  [sym_field_name] = sym_field_name,
  [aux_sym_module_body_repeat1] = aux_sym_module_body_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_union_body_repeat1] = aux_sym_union_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_module_name] = {
    .visible = true,
    .named = true,
  },
  [sym_module_body] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_union_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_union_name] = {
    .visible = true,
    .named = true,
  },
  [sym_union_body] = {
    .visible = true,
    .named = true,
  },
  [sym_union_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        ';', 26,
        '=', 25,
        'm', 10,
        's', 14,
        't', 18,
        'u', 8,
        '{', 22,
        '}', 1,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ';') ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(2);
      END_STATE();
    case 18:
      if (lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == '}') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 19},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 19},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 19},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 19},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 19},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_SEMI] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym_module_definition] = STATE(30),
    [anon_sym_module] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_RBRACE_SEMI,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_union,
    STATE(3), 4,
      sym_type_definition,
      sym_struct_definition,
      sym_union_definition,
      aux_sym_module_body_repeat1,
  [19] = 5,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_union,
    ACTIONS(13), 1,
      anon_sym_RBRACE_SEMI,
    STATE(4), 4,
      sym_type_definition,
      sym_struct_definition,
      sym_union_definition,
      aux_sym_module_body_repeat1,
  [38] = 5,
    ACTIONS(15), 1,
      anon_sym_RBRACE_SEMI,
    ACTIONS(17), 1,
      anon_sym_type,
    ACTIONS(20), 1,
      anon_sym_struct,
    ACTIONS(23), 1,
      anon_sym_union,
    STATE(4), 4,
      sym_type_definition,
      sym_struct_definition,
      sym_union_definition,
      aux_sym_module_body_repeat1,
  [57] = 4,
    ACTIONS(26), 1,
      anon_sym_RBRACE_SEMI,
    ACTIONS(28), 1,
      sym_identifier,
    STATE(27), 1,
      sym_field_type,
    STATE(6), 2,
      sym_union_field,
      aux_sym_union_body_repeat1,
  [71] = 4,
    ACTIONS(30), 1,
      anon_sym_RBRACE_SEMI,
    ACTIONS(32), 1,
      sym_identifier,
    STATE(27), 1,
      sym_field_type,
    STATE(6), 2,
      sym_union_field,
      aux_sym_union_body_repeat1,
  [85] = 4,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RBRACE_SEMI,
    STATE(24), 1,
      sym_field_type,
    STATE(8), 2,
      sym_struct_field,
      aux_sym_struct_body_repeat1,
  [99] = 4,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_RBRACE_SEMI,
    STATE(24), 1,
      sym_field_type,
    STATE(10), 2,
      sym_struct_field,
      aux_sym_struct_body_repeat1,
  [113] = 4,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RBRACE_SEMI,
    STATE(27), 1,
      sym_field_type,
    STATE(5), 2,
      sym_union_field,
      aux_sym_union_body_repeat1,
  [127] = 4,
    ACTIONS(41), 1,
      anon_sym_RBRACE_SEMI,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(24), 1,
      sym_field_type,
    STATE(10), 2,
      sym_struct_field,
      aux_sym_struct_body_repeat1,
  [141] = 1,
    ACTIONS(46), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [148] = 1,
    ACTIONS(48), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [155] = 1,
    ACTIONS(50), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [162] = 1,
    ACTIONS(52), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [169] = 1,
    ACTIONS(54), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [176] = 1,
    ACTIONS(56), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [183] = 1,
    ACTIONS(58), 4,
      anon_sym_RBRACE_SEMI,
      anon_sym_type,
      anon_sym_struct,
      anon_sym_union,
  [190] = 2,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_module_body,
  [197] = 2,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(18), 1,
      sym_module_name,
  [204] = 2,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(28), 1,
      sym_union_name,
  [211] = 2,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(33), 1,
      sym_type_body,
  [218] = 2,
    ACTIONS(68), 1,
      sym_identifier,
    STATE(38), 1,
      sym_type_name,
  [225] = 2,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(26), 1,
      sym_struct_name,
  [232] = 2,
    ACTIONS(72), 1,
      sym_identifier,
    STATE(41), 1,
      sym_field_name,
  [239] = 1,
    ACTIONS(74), 2,
      anon_sym_RBRACE_SEMI,
      sym_identifier,
  [244] = 2,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_struct_body,
  [251] = 2,
    ACTIONS(72), 1,
      sym_identifier,
    STATE(42), 1,
      sym_field_name,
  [258] = 2,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_union_body,
  [265] = 1,
    ACTIONS(80), 2,
      anon_sym_RBRACE_SEMI,
      sym_identifier,
  [270] = 1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
  [274] = 1,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
  [278] = 1,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
  [282] = 1,
    ACTIONS(88), 1,
      anon_sym_SEMI,
  [286] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
  [290] = 1,
    ACTIONS(92), 1,
      anon_sym_SEMI,
  [294] = 1,
    ACTIONS(94), 1,
      sym_identifier,
  [298] = 1,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
  [302] = 1,
    ACTIONS(98), 1,
      anon_sym_EQ,
  [306] = 1,
    ACTIONS(100), 1,
      anon_sym_EQ,
  [310] = 1,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
  [314] = 1,
    ACTIONS(104), 1,
      anon_sym_SEMI,
  [318] = 1,
    ACTIONS(106), 1,
      anon_sym_SEMI,
  [322] = 1,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
  [326] = 1,
    ACTIONS(110), 1,
      anon_sym_SEMI,
  [330] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 71,
  [SMALL_STATE(7)] = 85,
  [SMALL_STATE(8)] = 99,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 127,
  [SMALL_STATE(11)] = 141,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 155,
  [SMALL_STATE(14)] = 162,
  [SMALL_STATE(15)] = 169,
  [SMALL_STATE(16)] = 176,
  [SMALL_STATE(17)] = 183,
  [SMALL_STATE(18)] = 190,
  [SMALL_STATE(19)] = 197,
  [SMALL_STATE(20)] = 204,
  [SMALL_STATE(21)] = 211,
  [SMALL_STATE(22)] = 218,
  [SMALL_STATE(23)] = 225,
  [SMALL_STATE(24)] = 232,
  [SMALL_STATE(25)] = 239,
  [SMALL_STATE(26)] = 244,
  [SMALL_STATE(27)] = 251,
  [SMALL_STATE(28)] = 258,
  [SMALL_STATE(29)] = 265,
  [SMALL_STATE(30)] = 270,
  [SMALL_STATE(31)] = 274,
  [SMALL_STATE(32)] = 278,
  [SMALL_STATE(33)] = 282,
  [SMALL_STATE(34)] = 286,
  [SMALL_STATE(35)] = 290,
  [SMALL_STATE(36)] = 294,
  [SMALL_STATE(37)] = 298,
  [SMALL_STATE(38)] = 302,
  [SMALL_STATE(39)] = 306,
  [SMALL_STATE(40)] = 310,
  [SMALL_STATE(41)] = 314,
  [SMALL_STATE(42)] = 318,
  [SMALL_STATE(43)] = 322,
  [SMALL_STATE(44)] = 326,
  [SMALL_STATE(45)] = 330,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_body_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_body_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_body_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_body_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_body, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_body, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_body, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_name, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_name, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_adl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "adl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
